-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 22:05:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema control_empleados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control_empleados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_empleados` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `control_empleados` ;

-- -----------------------------------------------------
-- Table `control_empleados`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_empleados`.`empleados` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_6fdpo2x5rmegfbngre7xb3yoh` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
